env:
    MANIFEST: https://gitlab.com/OrangeFox/Manifest.git
    MANIFEST_BRANCH: fox_9.0
    DEVICE: juice
    DT_LINK: https://github.com/Joaquin-000/orangefox_device_xiaomi_juice.git
    DT_PATH: device/xiaomi/juice
    TARGET: recoveryimage

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G
  
  Sync_script:
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 --no-repo-verify -u $MANIFEST -b $MANIFEST_BRANCH -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone $DT_LINK $DT_PATH

  Build_script:
      - cd ~/work
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export LC_ALL="C"
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch omni_$DEVICE-eng
      - mka $TARGET
     
  Upload_script:
      - cd ~/work
      - cd out/target/product/$DEVICE
      - ls -lh
      - curl -sL https://git.io/file-transfer | sh 
      - ./transfer wet *.zip
